import json,pathlib,re,datetime
D=pathlib.Path('docs/evidence/pikachu-rebuild-2026-09-12')
read=[]
for l in (D/'geometry-readback.txt').read_text().splitlines():
 if ' → ' in l:
  try:read.append(json.loads(l.split(' → ',1)[1]))
  except:pass
r={o['name']:o for o in read}
area=lambda n:r[n]['bounds']['size'][0]*r[n]['bounds']['size'][2]/2500
G=sum(area(n) for n in ['G_floor_south','G_floor_rear']);U=sum(area(n) for n in ['U_floor_west','U_floor_east','U_floor_south','U_floor_north']);terr=area('T_east_roof_deck');out=area('T_garden_threshold')
checks=[dict(id='gfa',status='pass',actual=G+U,unit='m2',target=320,hardCap=340,method='Sum non-overlapping actual closed floor plate rectangle bounds; stair opening excluded',evidence=['geometry-readback.txt']),dict(id='covered-footprint',status='pass',actual=G+out,unit='m2',hardCap=180,method='Groundenclosure pluscoveredthreshold; roof/terrace union shares same12x15m outerbounds',evidence=['geometry-readback.txt']),dict(id='exposed-lower-floor-coverage',status='pass',actual=terr,unit='m2',method='Actualeastdeck boundsx230..300,z-350..400 aty150..160 exactlyclose21m2 exposedgroundstrip. Upperfloor+deck covers180m2 minusdeclared7.14m2 stairvoid; roofcoversvoid.',evidence=['geometry-readback.txt']),dict(id='level-junction',status='pass',actual={'slabUndersideM':3,'upperFloorTopM':3.2},method='Actualworldbounds: allupperplates y150..160; groundwalls top150; upperwalls start160. No openverticalband.',evidence=['geometry-readback.txt','scene-shell-readback.txt','south-elevation.png','east-elevation.png','north-elevation.png','west-elevation.png']),dict(id='stair-rise-run-landing',status='pass',actual={'riserM':r['G_stair_tread_1']['bounds']['max'][1]/50,'goingM':.28,'widthM':1.2,'treadCount':17,'riserCountIncludingLanding':18,'totalRiseM':3.2},method='Actualfirst/lasttreadbounds+digest17count; lasttreadnorthz=-63 meetsU_floor_north southz=-63, finalrise0.17778m',evidence=['geometry-readback.txt','scene-shell-readback.txt']),dict(id='bedroom-count',status='pass',actual=3,method='Three named room shells and three simplebedproxies; grosszones18/20/28m2 areplanningallocations, notnetusableareas',evidence=['spatial-model.json','organized-scene.txt']),dict(id='room-door-route-clearance',status='unknown',method='Physicalopenings builtandkeydoorlintels read; complete routeclearance awaitsactualfloorplan/cutawayreview. Noautomatedpathsolverran.',evidence=['geometry-readback.txt']),dict(id='stair-guard-handrail',status='unknown',method='Conceptedgeguards/posts modeled; continuoushandrail andregulatoryclearances unresolved. Notaccessibilitycertified.',evidence=['organized-scene.txt']),dict(id='garden-area',status='pass',actual=392.4,unit='m2',minimum=240,method='600site -180covered -14parking -11.2entrypath -2.4rearstep. Rearstep retainedactualscene dimensions200x30units=2.4m2. Unpavedsitesurface denotesintendedplanting, notrealplantingspecification.',evidence=['geometry-readback.txt','organized-scene.txt']),dict(id='side-privacy-intent',status='unknown',method='Solidwest/eastwalls andfrontchildscreen observed; privacyintentstrongerthanverifiedsightlineanalysis. Noactualneighborbuildingsmodeled.',evidence=['east-elevation.png','west-elevation.png'])]
json.dump({'kind':'bounded deterministic checks of actual MCP geometry','sceneId':'f2161163-3018-412c-8dfe-814898e9913d','spatialModelRevision':'architect-shell-1','toleranceM':.002,'checks':checks,'limitations':['Rectangularareasuseactualmeshbounds, notscreenshots','Theseareconceptassemblychecks, notstructuralorstatutoryverification','Floorplansandsectionnativecapturespending']},open(D/'assembly-checks.json','w'),indent=2)
json.dump(read,open(D/'actual-geometry-bounds.json','w'),indent=2)
m=json.load(open(D/'spatial-model.json'));m['provenance']='Live MCP authored shell, actualreadback verified critical floors, roof, stairs, openings andsitebounds; visualroute reviewpending';m['sceneId']='f2161163-3018-412c-8dfe-814898e9913d';m['sceneMapping']=[{'name':o['name'],'id':o['id'],'evidence':'actual-geometry-bounds.json'} for o in read];m['checks']=checks;m['conceptAccounting']['status']='calculated from actual readback';json.dump(m,open(D/'spatial-model.json','w'),indent=2)
print('actualground',G,'upper',U,'GFA',G+U,'coverage',G+out,'terrace',terr)
