import { Design, DesignElement } from './design';

export function exampleDesign(): Design {
  const elements: DesignElement[] = [];
  const add = (id: string, kind: DesignElement['kind'], name: string, position: [number, number, number], size: [number, number, number], materialId: string, floor = 0) => elements.push({ id, kind, name, position, size, materialId, floor, rotation: 0, assetId: null });
  add('ground-slab', 'slab', 'Ground floor', [0, -.12, 0], [14, .24, 10], 'concrete');
  add('back-wall-left', 'wall', 'Exterior north left', [-5.25, 1.5, -5], [3.5, 3, .18], 'exterior');
  add('back-wall-right', 'wall', 'Exterior north right', [5.25, 1.5, -5], [3.5, 3, .18], 'exterior');
  add('back-wall-sill', 'wall', 'Garden window sill', [0, .15, -5], [7, .3, .18], 'exterior');
  add('back-wall-header', 'wall', 'Garden window header', [0, 2.85, -5], [7, .3, .18], 'exterior');
  add('west-wall', 'wall', 'Exterior west', [-7, 1.5, 0], [.18, 3, 10], 'exterior');
  add('east-wall', 'wall', 'Exterior east', [7, 1.5, 0], [.18, 3, 10], 'exterior');
  add('front-left', 'wall', 'Entrance facade left', [-4.1, 1.5, 5], [5.8, 3, .18], 'exterior');
  add('front-right', 'wall', 'Entrance facade right', [4.1, 1.5, 5], [5.8, 3, .18], 'exterior');
  add('entrance', 'door', 'Main entrance', [0, 1.2, 5], [2.2, 2.4, .08], 'oak');
  add('glazing', 'window', 'Garden glazing', [0, 1.5, -4.88], [7, 2.4, .05], 'glass');
  add('sofa', 'furniture', 'Living room sofa', [-3.8, .45, 0], [3.2, .9, 1.1], 'linen');
  add('coffee-table', 'furniture', 'Coffee table', [-3.8, .24, 1.5], [1.6, .48, .8], 'oak');
  add('dining-table', 'furniture', 'Dining table', [3, .4, -1], [2.4, .8, 1.2], 'oak');
  for (let i = 0; i < 4; i++) add(`chair-${i}`, 'furniture', 'Dining chair', [2.3 + (i % 2) * 1.4, .45, -1 + (i < 2 ? -1.2 : 1.2)], [.55, .9, .55], 'linen');
  add('roof', 'roof', 'Flat roof', [0, 3.15, 0], [14.5, .25, 10.5], 'concrete');
  for (const e of elements) { if (e.id==='sofa') e.assetId='atelier-sofa'; else if (e.id.includes('table')) e.assetId='atelier-table'; else if (e.id.startsWith('chair')) e.assetId='atelier-chair'; }
  return {
    schemaVersion: 1, units: 'meters', title: 'The Courtyard House', buildingType: 'residential', floors: 1, assets:[],
    materials: [
      { id: 'exterior', name: 'Ochre plaster', color: '#c7a764', roughness: .8, metalness: 0 },
      { id: 'concrete', name: 'Warm concrete', color: '#bfb9aa', roughness: .85, metalness: 0 },
      { id: 'oak', name: 'Natural oak', color: '#9b7350', roughness: .6, metalness: 0 },
      { id: 'linen', name: 'Ivory linen', color: '#e0d7c4', roughness: 1, metalness: 0 },
      { id: 'glass', name: 'Clear glass', color: '#bad0cb', roughness: .1, metalness: .1 },
    ],
    spaces: [
      { id: 'living', name: 'Living & lounge', floor: 0, position: [-3.5, 1.5, 0], size: [6.5, 3, 9] },
      { id: 'dining', name: 'Kitchen & dining', floor: 0, position: [3.5, 1.5, 0], size: [6.5, 3, 9] },
    ], elements, spawn: [0, 1.7, 3], notes: ['Sample project for exploring the studio. This was not generated by an AI run.'],
  };
}
